<div class="right-top col-sm-12 sticky-top">
    <div class="right-top-text col-sm-12 no-gutters bg-dark">
        <button type="button" class="btn btn-primary btn-sm active">全部</button>
        <button type="button" class="btn btn-outline-primary btn-sm">PHP</button>
        <button type="button" class="btn btn-outline-secondary btn-sm">前端</button>
        <button type="button" class="btn btn-outline-warning btn-sm">后端</button>
        <button type="button" class="btn btn-outline-success btn-sm">Git</button>
        <button type="button" class="btn btn-outline-danger btn-sm">Linux</button>
        <button type="button" class="btn btn-dark btn-sm">Dark</button>
    </div>
</div>

<div class="right-content col-sm-10">
    <?php echo $this->getContent(); ?>
</div>

<div class="right-sidebar col-sm-2">
    <?php $this->partial("shared/sidebar"); ?>
</div>