<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>瓜子皮 - Goozp's Blog</title>
    <?php
    /* HTML 头部资源 */
    echo $this->tag->stylesheetLink("themes/default/public/library/bootstrap/css/bootstrap.min.css"); // Bootstrap
    echo $this->tag->stylesheetLink("themes/default/public/library/font-awesome-4.7.0/css/font-awesome.min.css"); // Bootstrap
    echo $this->tag->stylesheetLink("themes/default/public/css/globals.css");
    ?>
</head>
<body
    <div class="container-fluid">
        <div class="row">
            <div class="author col-12 d-sm-block col-md-2 col-md-2 col-xl-1 flex-lg-column">
                <?php $this->partial("shared/author"); ?>
            </div>

            <div class="right col-12 d-sm-block ml-sm-auto col-md-10 col-xl-11" role="main">
                <div class="row">
                    <!-- 加载common模块 -->
                    <?php echo $this->getContent(); ?>

                    <!-- 加载footer -->
                    <footer class="footer col-sm-12">
                        <?php $this->partial("shared/footer"); ?>
                    </footer>
                </div>
            </div>
        </div>
    </div>

    <?php
        /* HTML尾部资源 */
        echo $this->tag->javascriptInclude("themes/default/public/js/vendor/jquery-slim.min.js");
        echo $this->tag->javascriptInclude("themes/default/public/js/vendor/popper.min.js");
        echo $this->tag->javascriptInclude("themes/default/public/library/bootstrap/js/bootstrap.min.js");
        echo $this->tag->javascriptInclude("themes/default/public/js/ie10-viewport-bug-workaround.js");
    ?>
</body>
</html>
