<div class="row">
    <div class="author-top col-12 text-md-center">
        <img src="https://www.gzpblog.com/wp-content/themes/SaltedFish/public/images/jumbotron_self.png"
                 class="rounded-circle mx-auto d-block img-fluid" alt="..." width="110" height="110">
        <p class="author-name"><strong>Goozp</strong></p>
        <p class="author-subname">PHP开发工程师，奋斗的扫地工</p>
    </div>

    <nav class="col-12 author-nav nav flex-md-column text-md-center mt-2">
        <a class="nav-link active" href="#"><i class="fa fa-paint-brush"></i> 文章</a>
        <a class="nav-link" href="#"><i class="fa fa-book"></i> 专题</a>
        <a class="nav-link" href="#"><i class="fa fa-github"></i> 作品</a>
        <a class="nav-link" href="#"><i class="fa fa-archive"></i> 归档</a>
        <a class="nav-link" href="#"><i class="fa fa-link"></i> 友链</a>
        <a class="nav-link" href="#"><i class="fa fa-heart"></i> 关于</a>
    </nav>

    <div class="col-12 text-center mt-3">
        <a href="#" class="i_weibo" target="_blank" rel="external nofollow"><i class="fa fa-feed "></i></a>&nbsp;
        <a href="http://weibo.com/zpguo/home?wvr=5&lf=reg" class="i_weibo" target="_blank" rel="external nofollow"><i class="fa fa-weibo"></i></a>&nbsp;
        <a href="https://github.com/ZpGuo" class="i_github" target="_blank" rel="external nofollow"><i class="fa fa-github"></i></a>&nbsp;
        <a href="#" class="i_facebook" target="_blank" rel="external nofollow"><i class="fa fa-facebook-square"></i></a>
    </div>

    <div class="author-motto">
        <p>“当你发现自己的才华撑不起野心时，就请安静下来学习吧。”</p>
    </div>
</div>
