<header class="main-header">
    <!-- Logo -->
    <a href="<?php echo $this->url->get("admin"); ?>" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>Z</b>P</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Z</b>Phal</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

            </ul>
        </div>
    </nav>
</header>

<!-- =============================================== -->

<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- 侧边菜单 sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">主菜单</li>
            <li class="treeview <?php if ($controllerName=='index') echo 'active'; ?>">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>仪表盘</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                </a>
                <ul class="treeview-menu">
                    <li <?php if ($controllerName=='index' && $actionName=='index') echo 'class="active"'; ?>>
                        <a href="<?php echo $this->url->get("admin/"); ?>"><i class="fa fa-circle-o"></i> 首页 </a>
                    </li>
                </ul>
            </li>

            <li class="treeview <?php if ($controllerName=='post') echo 'active'; ?>">
                <a href="#">
                    <i class="fa fa-files-o"></i> <span>文章</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                </a>
                <ul class="treeview-menu">
                    <li <?php if ($controllerName=='post' && $actionName=='index') echo 'class="active"'; ?>>
                        <a href="<?= $this->url->get("admin/post"); ?>"><i class="fa fa-circle-o"></i> 所有文章</a>
                    </li>
                    <li <?php if ($controllerName=='post' && $actionName=='new') echo 'class="active"'; ?>>
                        <a href="<?= $this->url->get("admin/post/new"); ?>"><i class="fa fa-circle-o"></i> 写文章</a>
                    </li>
                    <li <?php if ($controllerName=='post' && $actionName=='taxonomy' && $type=='category') echo 'class="active"'; ?>>
                        <a href="<?= $this->url->get("admin/post/taxonomy/category"); ?>"><i class="fa fa-circle-o"></i> 分类目录</a>
                    </li>
                    <li <?php if ($controllerName=='post' && $actionName=='taxonomy' && $type=='tag') echo 'class="active"'; ?>>
                        <a href="<?= $this->url->get("admin/post/taxonomy/tag"); ?>"><i class="fa fa-circle-o"></i> 标签</a>
                    </li>
                </ul>
            </li>

            <li class="treeview <?php if ($controllerName=='subject') echo 'active'; ?>">
                <a href="#">
                    <i class="fa fa-dashcube"></i> <span>专题</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                </a>
                <ul class="treeview-menu">
                    <li  <?php if ($controllerName=='subject' && $actionName=='index') echo 'class="active"'; ?>>
                        <a href="<?= $this->url->get("admin/subject"); ?>"><i class="fa fa-circle-o"></i> 专题管理</a>
                    </li>
                    <li  <?php if ($controllerName=='subject' && $actionName=='new') echo 'class="active"'; ?>>
                        <a href="<?= $this->url->get("admin/subject/new"); ?>"><i class="fa fa-circle-o"></i> 添加</a>
                    </li>
                </ul>
            </li>

            <li class="treeview <?php if ($controllerName=='media') echo 'active'; ?>">
                <a href="#">
                    <i class="fa fa-medium"></i> <span>媒体</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                </a>
                <ul class="treeview-menu">
                    <li <?php if ($controllerName=='media' && $actionName=='index') echo 'class="active"'; ?>>
                        <a href="<?= $this->url->get("admin/media"); ?>"><i class="fa fa-circle-o"></i> 媒体库</a>
                    </li>
                    <li <?php if ($controllerName=='media' && $actionName=='new') echo 'class="active"'; ?>>
                        <a href="<?= $this->url->get("admin/media/new"); ?>"><i class="fa fa-circle-o"></i> 添加</a>
                    </li>
                </ul>
            </li>

            <li class="treeview <?php if ($controllerName=='link') echo 'active'; ?>">
                <a href="#">
                    <i class="fa fa-link"></i>
                    <span>链接</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                </a>
                <ul class="treeview-menu">
                    <li <?php if ($controllerName=='link' && $actionName=='index') echo 'class="active"'; ?>>
                        <a href="<?= $this->url->get("admin/link"); ?>"><i class="fa fa-circle-o"></i> 全部链接</a>
                    </li>
                    <li <?php if ($controllerName=='link' && $actionName=='new') echo 'class="active"'; ?>>
                        <a href="<?= $this->url->get("admin/link/new"); ?>"><i class="fa fa-circle-o"></i> 添加</a>
                    </li>
                    <li <?php if ($controllerName=='link' && $actionName=='linkCategory') echo 'class="active"'; ?>>
                        <a href="<?= $this->url->get("admin/link/linkCategory"); ?>"><i class="fa fa-circle-o"></i> 链接分类目录</a>
                    </li>
                </ul>
            </li>

            <li class="treeview">
                <a href="#">
                    <i class="fa fa-sticky-note-o"></i>
                    <span>页面</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> 所有页面</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> 新建页面</a></li>
                </ul>
            </li>

            <li>
                <a href="#">
                    <i class="fa fa-comments-o"></i> <span>评论</span>
                    <span class="pull-right-container">
                            <small class="label pull-right bg-green">new</small>
                        </span>
                </a>
            </li>



            <li class="header">功能</li>

            <li class="treeview <?php if ($controllerName=='user') echo 'active'; ?>">
                <a href="#">
                    <i class="fa fa-user"></i> <span>用户</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                </a>
                <ul class="treeview-menu">
                    <li <?php if ($controllerName=='user' && $actionName=='index') echo 'class="active"'; ?>>
                        <a href="<?php echo $this->url->get("admin/user"); ?>">
                            <i class="fa fa-circle-o"></i> 所有用户
                        </a>
                    </li>
                    <li <?php if ($controllerName=='user' && $actionName=='new') echo 'class="active"'; ?>>
                        <a href="<?php echo $this->url->get("admin/user/new"); ?>">
                            <i class="fa fa-circle-o"></i> 添加用户
                        </a>
                    </li>
                    <li <?php if ($controllerName=='user' && $actionName=='self') echo 'class="active"'; ?>>
                        <a href="<?php echo $this->url->get("admin/user/self"); ?>">
                            <i class="fa fa-circle-o"></i> 我的个人资料
                        </a>
                    </li>
                </ul>
            </li>

            <li class="treeview <?php if ($controllerName=='setting') echo 'active'; ?>">
                <a href="#">
                    <i class="fa fa-cogs"></i> <span>设置</span>
                    <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                </a>
                <ul class="treeview-menu">
                    <li <?php if ($controllerName=='setting' && $actionName=='general') echo 'class="active"'; ?>>
                        <a href="<?php echo $this->url->get("admin/setting/general"); ?>">
                            <i class="fa fa-circle-o"></i> 常规
                        </a>
                    </li>
                    <li <?php if ($controllerName=='setting' && $actionName=='writing') echo 'class="active"'; ?>>
                        <a href="<?php echo $this->url->get("admin/setting/writing"); ?>">
                            <i class="fa fa-circle-o"></i> 撰写
                        </a>
                    </li>
                    <li <?php if ($controllerName=='setting' && $actionName=='reading') echo 'class="active"'; ?>>
                        <a href="<?php echo $this->url->get("admin/setting/reading"); ?>">
                            <i class="fa fa-circle-o"></i> 阅读
                        </a>
                    </li>
                    <li <?php if ($controllerName=='setting' && $actionName=='discuss') echo 'class="active"'; ?>>
                        <a href="<?php echo $this->url->get("admin/setting/discuss"); ?>">
                            <i class="fa fa-circle-o"></i> 讨论
                        </a>
                    </li>
                    <li <?php if ($controllerName=='setting' && $actionName=='media') echo 'class="active"'; ?>>
                        <a href="<?php echo $this->url->get("admin/setting/media"); ?>">
                            <i class="fa fa-circle-o"></i> 媒体
                        </a>
                    </li>
                    <li <?php if ($controllerName=='setting' && $actionName=='permalink') echo 'class="active"'; ?>>
                        <a href="<?php echo $this->url->get("admin/setting/permalink"); ?>">
                            <i class="fa fa-circle-o"></i> 固定链接
                        </a>
                    </li>
                </ul>
            </li>

            <li class="header">标签颜色</li>
            <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>重要</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>提醒</span></a></li>
            <li><a href="#"><i class="fa fa-circle-o text-green"></i> <span>信息</span></a></li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>