<!-- 页头 -->
<section class="content-header">
    <div class="msgTip col-md-12">
        <div class="row">
            <?php $this->flash->output(); ?>
        </div>
    </div>
    <h1>
        新专题
        <small>添加一个新专题，专题可以有层级关系</small>
    </h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <form class="form-horizontal" action="<?= $this->url->get(["for" => "save-subject"]); ?>" method="post">
                <div class="box box-default box-solid">
                    <div class="box-header with-border">
                        <h3 class="box-title">添加新的分类目录</h3>
                    </div>

                    <div class="box-body">
                        <div class="container">
                            <div class="form-group">
                                <label for="inputUser" class="col-sm-2 control-label">专题名称</label>
                                <div class="col-sm-6">
                                    <input type="text" name="name" class="form-control" id="name" placeholder="名称">
                                    <span class="help-block">名称是在站点上显示的名字。</span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="inputEmail" class="col-sm-2 control-label">别名</label>
                                <div class="col-sm-6">
                                    <input type="text" name="slug" class="form-control" id="slug" placeholder="别名">
                                    <span class="help-block">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label">父级专题</label>
                                <div class="col-sm-6">
                                    <select class="form-control" name="parent">
                                        <?= $categoryTree ?>
                                    </select>
                                    <span class="help-block">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="inputFile" class="col-sm-2 control-label">封面图</label>
                                <div class="col-sm-8">
                                    <input type="file" name="file" id="inputFile">
                                    <span class="help-block">一张该主题的封面图，可能展示在主题页面中。</span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="desc" class="col-sm-2 control-label">描述</label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" id="desc" rows="3" placeholder="写一点东西吧..." name="description"></textarea>
                                    <span class="help-block">关于该分类目录的描述。</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="box-footer  text-center">
                        <button type="submit" class="btn btn-info">添加新主题</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>