<div class="row no-gutters">
    <div class="article-card article-word-card col-12">
        <div class="d-flex flex-column">
            <div class="p-2 flex-column-item">
                <h6 class="card-subtitle mt-1 text-muted">
                    <i class="fa fa-calendar-check-o"></i> 2017-08-01 10:23&nbsp;&nbsp;
                    <i class="fa fa-tags"></i> <a href="#">前端综合 前端综合 前端综合 前端综合 前端综合</a>&nbsp;
                    <i class="fa fa-eye"></i> 28 阅读&nbsp;
                    <i class="fa fa-comments-o"></i> 2条回复
                </h6>
            </div>
            <div class="article-card-body">
                <div class="p-2 flex-column-item">
                    <div class="mt-2">
                        <h4 class="card-title"><a href="#">火狐浏览器X-Content-Type-Options导致Images类型无法加载</a></h4>
                        <p class="card-text">1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页面总是出现菊花一直在转，
                            左下角一直在等待sp0.baidu.com： 导致后面的js无法加载。看了一下 network 发现是获取一个 s.gif 的时候出现问题：
                            具体的url： 而这个问题只在火狐上出现，其它浏览器正常，比如chrome浏览器正常加载： 同时在火狐上报了一个错...</p>
                    </div>
                </div>
            </div>
            <div class="d-flex justify-content-start flex-wrap">
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">Guzzle</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">HTTP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">PHP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">HTTP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">Guzzle</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">HTTP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">PHP</a></div>
                <div class="button-detail ml-auto btn btn-outline-dark">阅读全文</div>
            </div>
        </div>
    </div>

    <div class="article-card article-img-card col-12">
        <div class="d-flex flex-column">
            <div class="p-2 flex-column-item">
                <h6 class="card-subtitle mt-1 text-muted">
                    <i class="fa fa-calendar-check-o"></i> 2017-08-01 10:23&nbsp;&nbsp;
                    <i class="fa fa-tags"></i> <a href="#">前端综合</a>&nbsp;
                    <i class="fa fa-eye"></i> 28 阅读&nbsp;
                    <i class="fa fa-comments-o"></i> 2条回复
                </h6>
            </div>
            <div class="article-card-body">
                <div class="p-2 flex-column-item">
                    <div class="row no-gutters">
                        <div class="article-card-img col-xs-12 text-xs-center col-md-3 m-auto">
                            <a href="#">
                            <?php echo $this->tag->image([
                                "themes/default/public/images/self.png",
                                "class"=>"img-thumbnail img-fluid mx-auto d-block",
                                "alt" => "img",
                                "height" => 150,
                                "width" => 150
                            ]);?>
                            </a>
                        </div>
                        <div class="article-card-body col-xs-12 col-md-9 mt-2">
                            <h4 class="card-title"><a href="#">火狐浏览器X-Content-Type-Options导致Images类型无法加载</a></h4>
                            <p class="card-text">1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页面总是出现菊花一直在转，
                                左下角一直在等待sp0.baidu.com： 导致后面的js无法加载。看了一下 network 发现是获取一个 s.gif 的时候出现问题
                                ： 具体的url： 而这个问题只在火狐上出现，其它浏览器正常，比如chrome浏览器正常加载：
                                同时在火狐上报了一个错...</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="d-flex justify-content-start flex-wrap">
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">Guzzle</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">HTTP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">PHP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">HTTP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">Guzzle</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">HTTP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">PHP</a></div>
                <div class="button-detail ml-auto btn btn-outline-dark border-top-0 border-right-0 border-bottom-0">阅读全文</div>
            </div>
        </div>
    </div>

    <div class="article-card article-word-card col-12">
        <div class="d-flex flex-column">
            <div class="p-2 flex-column-item">
                <h6 class="card-subtitle mt-1 text-muted">
                    <i class="fa fa-calendar-check-o"></i> 2017-08-01 10:23&nbsp;&nbsp;
                    <i class="fa fa-tags"></i> <a href="#">前端综合 前端综合 前端综合 前端综合 前端综合</a>&nbsp;
                    <i class="fa fa-eye"></i> 28 阅读&nbsp;
                    <i class="fa fa-comments-o"></i> 2条回复
                </h6>
            </div>
            <div class="article-card-body">
                <div class="p-2 flex-column-item">
                    <div class="mt-2">
                        <h4 class="card-title"><a href="#">火狐浏览器X-Content-Type-Options导致Images类型无法加载</a></h4>
                        <p class="card-text">1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页面总是出现菊花一直在转，
                            左下角一直在等待sp0.baidu.com： 导致后面的js无法加载。看了一下 network 发现是获取一个 s.gif 的时候出现问题：
                            具体的url： 而这个问题只在火狐上出现，其它浏览器正常，比如chrome浏览器正常加载： 同时在火狐上报了一个错...</p>
                    </div>
                </div>
            </div>
            <div class="d-flex justify-content-start flex-wrap">
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">Guzzle</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">HTTP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">PHP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">HTTP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">Guzzle</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">HTTP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">PHP</a></div>
                <div class="button-detail ml-auto btn btn-outline-dark">阅读全文</div>
            </div>
        </div>
    </div>

    <div class="article-card article-img-card col-12">
        <div class="d-flex flex-column">
            <div class="p-2 flex-column-item">
                <h6 class="card-subtitle mt-1 text-muted">
                    <i class="fa fa-calendar-check-o"></i> 2017-08-01 10:23&nbsp;&nbsp;
                    <i class="fa fa-tags"></i> <a href="#">前端综合</a>&nbsp;
                    <i class="fa fa-eye"></i> 28 阅读&nbsp;
                    <i class="fa fa-comments-o"></i> 2条回复
                </h6>
            </div>
            <div class="article-card-body">
                <div class="p-2 flex-column-item">
                    <div class="row no-gutters">
                        <div class="article-card-img col-xs-12 text-xs-center col-md-3 m-auto">
                            <a href="#">
                                <?php echo $this->tag->image([
                                    "themes/default/public/images/self.png",
                                    "class"=>"img-thumbnail img-fluid mx-auto d-block",
                                    "alt" => "img",
                                    "height" => 150,
                                    "width" => 150
                                ]);?>
                            </a>
                        </div>
                        <div class="article-card-body col-xs-12 col-md-9 mt-2">
                            <h4 class="card-title"><a href="#">火狐浏览器X-Content-Type-Options导致Images类型无法加载</a></h4>
                            <p class="card-text">1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页面总是出现菊花一直在转，
                                左下角一直在等待sp0.baidu.com： 导致后面的js无法加载。看了一下 network 发现是获取一个 s.gif 的时候出现问题
                                ： 具体的url： 而这个问题只在火狐上出现，其它浏览器正常，比如chrome浏览器正常加载：
                                同时在火狐上报了一个错...</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="d-flex justify-content-start flex-wrap">
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">Guzzle</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">HTTP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">PHP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">HTTP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">Guzzle</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">HTTP</a></div>
                <div class="p-1 "><a href="#" class="badge badge-pill badge-secondary">PHP</a></div>
                <div class="button-detail ml-auto btn btn-outline-dark border-top-0 border-right-0 border-bottom-0">阅读全文</div>
            </div>
        </div>
    </div>
</div>

