<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="masthead clearfix">
                <div class="inner">
                    <h3 class="masthead-brand">Goozp</h3>
                    <nav class="nav nav-masthead">
                        <a class="nav-link active" href="#">首页</a>
                        <a class="nav-link" href="https://www.gzpblog.com">博客</a>
                        <a class="nav-link" href="#">关于</a>
                    </nav>
                </div>
            </div>

            <div class="inner cover">
                <h1 class="cover-heading">博客正在施工中</h1>
                <p class="lead">最近正在重写一套属于自己的博客系统（Phalcon+bootstrap4），有兴趣可以先访问我的旧博客；链接：https://www.gzpblog.com</p>
                <p class="lead">
                    <a href="https://www.gzpblog.com" class="btn btn-lg btn-secondary">前往</a>
                </p>
            </div>

            <div class="mastfoot">
                <div class="inner">
                    <strong>Copyright &copy; 2017 <a href="https://www.goozp.com">goozp</a>.</strong> All rights reserved.
                </div>
            </div>
        </div>
    </div>
</div>
