<div class="row">
    <div class="article-card col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">火狐浏览器X-Content-Type-Options导致Images类型无法加载</h4>
                <h6 class="card-subtitle mb-2 text-muted"> 2017-08-01 10:23  前端综合  28 阅读  2 条回复</h6>
                <p class="card-text">1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页面总是出现菊花一直在转，左下角一直在等待sp0.baidu.com： 导致后面的js无法加载。看了一下 network 发现是获取一个 s.gif 的时候出现问题： 具体的url： 而这个问题只在火狐上出现，其它浏览器正常，比如chrome浏览器正常加载： 同时在火狐上报了一个错...</p>
                <a href="#" class="badge badge-pill badge-dark">Guzzle</a>
                <a href="#" class="badge badge-pill badge-dark">HTTP</a>
                <a href="#" class="badge badge-pill badge-dark">PHP</a>
                <a href="#" class="badge badge-pill badge-dark">HTTP</a>
                <a href="#" class="badge badge-pill badge-dark">Guzzle</a>
                <a href="#" class="badge badge-pill badge-dark">HTTP</a>
                <a href="#" class="badge badge-pill badge-dark">PHP</a>
                <a href="#" class="btn btn-outline-primary btn-sm float-right">阅读全文</a>
            </div>
        </div>
    </div>

    <div class="article-card-img col-sm-12">
        <div class="card">
            <div class="row">
                <div class="card-left col-sm-2">
                    <?php echo $this->tag->image([
                            "themes/default/public/images/default-img.png",
                            "class"=>"card-img-bottom img-thumbnail",
                            "alt" => "article img",
                        ]);?>
                </div>
                <div class="card-body col-sm-10">
                    <h4 class="card-title">火狐浏览器X-Content-Type-Options导致Images类型无法加载</h4>
                    <h6 class="card-subtitle mb-2 text-muted"> 2017-08-01 10:23  前端综合  28 阅读  2 条回复</h6>
                    <p class="card-text">1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页面总是出现菊花一直在转，左下角一直在等待sp0.baidu.com： 导致后面的js无法加载。看了一下 network 发现是获取一个 s.gif 的时候出现问题： 具体的url： 而这个问题只在火狐上出现，其它浏览器正常，比如chrome浏览器正常加载： 同时在火狐上报了一个错...</p>
                    <a href="#" class="badge badge-pill badge-primary">Guzzle</a>
                    <a href="#" class="badge badge-pill badge-secondary">HTTP</a>
                    <a href="#" class="badge badge-pill badge-success">PHP</a>
                    <a href="#" class="badge badge-pill badge-danger">HTTP</a>
                    <a href="#" class="badge badge-pill badge-warning">Guzzle</a>
                    <a href="#" class="badge badge-pill badge-info">HTTP</a>
                    <a href="#" class="badge badge-pill badge-dark">PHP</a>
                    <a href="#" class="btn btn-outline-primary btn-sm float-right">阅读全文</a>
                </div>
            </div>
        </div>
    </div>

    <div class="article-card col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">火狐浏览器X-Content-Type-Options导致Images类型无法加载火狐浏览器X-Content-Type-Options导致Images类型无法加载</h4>
                <h6 class="card-subtitle mb-2 text-muted"> 2017-08-01 10:23  前端综合  28 阅读  2 条回复</h6>
                <p class="card-text">1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页面总是出现菊花一直在转，左下角一直在等待sp0.baidu.com： 导致后面的js无法加载。看了一下 network 发现是获取一个 s.gif 的时候出现问题： 具体的url： 而这个问题只在火狐上出现，其它浏览器正常，比如chrome浏览器正常加载： 同时在火狐上报了一个错...</p>
                <a href="#" class="badge badge-pill badge-primary">Guzzle</a>
                <a href="#" class="badge badge-pill badge-primary">HTTP</a>
                <a href="#" class="badge badge-pill badge-primary">PHP</a>
                <a href="#" class="badge badge-pill badge-primary">HTTP</a>
                <a href="#" class="badge badge-pill badge-primary">Guzzle</a>
                <a href="#" class="badge badge-pill badge-primary">HTTP</a>
                <a href="#" class="badge badge-pill badge-primary">PHP</a>
                <a href="#" class="btn btn-outline-primary btn-sm float-right">阅读全文</a>
            </div>
        </div>
    </div>

    <div class="article-card-img col-sm-12">
        <div class="card">
            <div class="row">
                <div class="card-left col-sm-2">
                    <?php echo $this->tag->image([
                        "themes/default/public/images/default-img.png",
                        "class"=>"card-img-bottom img-thumbnail",
                        "alt" => "article img",
                    ]);?>
                </div>
                <div class="card-body col-sm-10">
                    <h4 class="card-title">火狐浏览器X-Content-Type-Options导致Images类型无法加载火狐浏览器X-Content-Type-Options导致Images类型无法加载</h4>
                    <h6 class="card-subtitle mb-2 text-muted"> 2017-08-01 10:23  前端综合  28 阅读  2 条回复</h6>
                    <p class="card-text">1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页面总是出现菊花一直在转，左下角一直在等待sp0.baidu.com： 导致后面的js无法加载。看了一下 network 发现是获取一个 s.gif 的时候出现问题： 具体的url： 而这个问题只在火狐上出现，其它浏览器正常，比如chrome浏览器正常加载： 同时在火狐上报了一个错...</p>
                    <a href="#" class="badge badge-pill badge-secondary">Guzzle</a>
                    <a href="#" class="badge badge-pill badge-secondary">HTTP</a>
                    <a href="#" class="badge badge-pill badge-secondary">PHP</a>
                    <a href="#" class="badge badge-pill badge-secondary">HTTP</a>
                    <a href="#" class="badge badge-pill badge-secondary">Guzzle</a>
                    <a href="#" class="badge badge-pill badge-secondary">HTTP</a>
                    <a href="#" class="badge badge-pill badge-secondary">PHP</a>
                    <a href="#" class="btn btn-outline-primary btn-sm float-right">阅读全文</a>
                </div>
            </div>
        </div>
    </div>

    <div class="article-card col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">火狐浏览器X-Content-Type-Options导致Images类型无法加载火狐浏览器X-Content-Type-Options导致Images类型无法加载</h4>
                <h6 class="card-subtitle mb-2 text-muted"> 2017-08-01 10:23  前端综合  28 阅读  2 条回复</h6>
                <p class="card-text">1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页面总是出现菊花一直在转，左下角一直在等待sp0.baidu.com： 导致后面的js无法加载。看了一下 network 发现是获取一个 s.gif 的时候出现问题： 具体的url： 而这个问题只在火狐上出现，其它浏览器正常，比如chrome浏览器正常加载： 同时在火狐上报了一个错...</p>
                <a href="#" class="badge badge-pill badge-primary">Guzzle</a>
                <a href="#" class="badge badge-pill badge-secondary">HTTP</a>
                <a href="#" class="badge badge-pill badge-success">PHP</a>
                <a href="#" class="badge badge-pill badge-danger">HTTP</a>
                <a href="#" class="badge badge-pill badge-warning">Guzzle</a>
                <a href="#" class="badge badge-pill badge-info">HTTP</a>
                <a href="#" class="badge badge-pill badge-dark">PHP</a>
                <a href="#" class="btn btn-outline-primary btn-sm float-right">阅读全文</a>
            </div>
        </div>
    </div>

    <div class="article-card col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">火狐浏览器X-Content-Type-Options导致Images类型无法加载火狐浏览器X-Content-Type-Options导致Images类型无法加载</h4>
                <h6 class="card-subtitle mb-2 text-muted"> 2017-08-01 10:23  前端综合  28 阅读  2 条回复</h6>
                <p class="card-text">1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页1. 发现问题 最近用火狐上博客时，发现一个问题，加载博客页面总是出现菊花一直在转，左下角一直在等待sp0.baidu.com： 导致后面的js无法加载。看了一下 network 发现是获取一个 s.gif 的时候出现问题： 具体的url： 而这个问题只在火狐上出现，其它浏览器正常，比如chrome浏览器正常加载： 同时在火狐上报了一个错...</p>
                <a href="#" class="badge badge-pill badge-primary">Guzzle</a>
                <a href="#" class="badge badge-pill badge-secondary">HTTP</a>
                <a href="#" class="badge badge-pill badge-success">PHP</a>
                <a href="#" class="badge badge-pill badge-danger">HTTP</a>
                <a href="#" class="badge badge-pill badge-warning">Guzzle</a>
                <a href="#" class="badge badge-pill badge-info">HTTP</a>
                <a href="#" class="badge badge-pill badge-dark">PHP</a>
                <a href="#" class="btn btn-outline-primary btn-sm float-right">阅读全文</a>
            </div>
        </div>
    </div>
</div>

