<style>
    .markdown-body {
        background-color: white;
        box-sizing: border-box;
        min-width: 200px;
        max-width: 980px;
        margin: 0 auto;
        padding: 45px;
    }

    @media (max-width: 767px) {
        .markdown-body {
            padding: 15px;
        }
    }
</style>
<div id="editormd-view" class="editormd">
    <div class="editormd-html-textarea markdown-body" name="editormd-view-html-code"><?= $content ?></div>
</div>
