<!-- 页头 -->
<section class="content-header">
    <div class="msgTip col-md-12">
        <div class="row">
            <?php $this->flash->output(); ?>
        </div>
    </div>
    <h1>
        编辑文章
        <small>固定链接:<span id="postUrl">暂无</span></small>
    </h1>
</section>

<!-- 主内容 -->
<section class="content">
    <div class="row">
        <div class="form-group col-md-12">
            <input class="form-control" id="title" type="text" name="title" placeholder="输入标题">
            <input type="hidden" id="post_id" name="post_id" value="0" >
        </div>

        <div class="form-group col-md-12">
            <div id="editormd">
                <textarea name="mr_content" style="display:none;"></textarea>
            </div>
        </div>

        <div class="form-group col-md-12">
            <label>Description</label>
            <textarea class="form-control" rows="3" name="description"  placeholder="概述"></textarea>
        </div>
    </div>
</section>