<!-- 页头 -->
<section class="content-header">
    <div class="msgTip col-md-12">
        <div class="row">
            <?php $this->flash->output(); ?>
        </div>
    </div>
    <h1>
        文章列表
    </h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <ul class="nav nav-pills " role="tablist">
                <li role="presentation" class="<?php if ($activeShow == 'all') echo 'bg-gray-active' ?>">
                    <a href="<?= $this->url->get(["for"=>"list-article","params"=>'all']); ?>">全部 <span class="badge"><?= array_sum($static) ?></span></a>
                </li>
                <li role="presentation" class="<?php if ($activeShow == 'publish') echo 'bg-gray-active' ?>">
                    <a href="<?= $this->url->get(["for"=>"list-article","params"=>'publish']); ?>">已发布 <span class="badge"><?= $static['publish_num'] ?></span></a>
                </li>
                <li role="presentation" class="<?php if ($activeShow == 'draft') echo 'bg-gray-active' ?>">
                    <a href="<?= $this->url->get(["for"=>"list-article","params"=>'draft']); ?>">草稿 <span class="badge"><?= $static['draft_num']+$static['autodraft_num'] ?></span></a>
                </li>
                <li role="presentation" class="<?php if ($activeShow == 'trash') echo 'bg-gray-active' ?>">
                    <a href="<?= $this->url->get(["for"=>"list-article","params"=>'trash']); ?>">回收站 <span class="badge"><?= $static['trash_num'] ?></span></a>
                </li>
            </ul>
        </div>

        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <form action="<?= $this->url->get(["for"=>"list-article","params"=>$activeShow]); ?>" method="get">

                        <div class="row">
                            <div class="col-xs-2">
                                <div class="input-group">
                                    <select class="form-control">
                                        <option>批量操作</option>
                                        <option>移至回收站</option>
                                    </select>
                                    <div class="input-group-btn">
                                        <button id="add-new-event" type="button" class="btn btn-default btn-flat">应用</button>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-8">
                                <div class="row">
                                    <div class="col-xs-3 col-xs-offset-1">
                                        <div class="input-group-btn">
                                            <select class="form-control" name="categorySelected">
                                                <?= $categoryTree; ?>
                                            </select>
                                        </div>

                                    </div>

                                    <div class="col-xs-3">
                                        <div class="input-group-btn">
                                            <select class="form-control" name="dateSelected">
                                                <option value="0">全部日期</option>
                                                <?php
                                                foreach ($dateSection as $date){ ?>
                                                    <option value="<?= $date['year_month'] ?>" <?php if ($dateSelected == $date['year_month']) echo 'selected'; ?>><?= $date['year_month'] ?></option>
                                                <?php } ?>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-xs-3">
                                        <div class="input-group">
                                            <button id="add-new-event" type="submit" class="btn btn-default btn-flat">筛选</button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-xs-2">
                                <div class="input-group">
                                    <input type="text" name="search" class="form-control pull-right" placeholder="标题关键字" value="<?= $search ?>">

                                    <div class="input-group-btn">
                                        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
               
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>标题</th>
                                <th>作者</th>
                                <th>分类目录</th>
                                <th>标签</th>
                                <th>评论 <i class="fa fa-comment"></i></th>
                                <th>日期</th>
                                <th>阅读量</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php
                        $result = $pager->getIterator();
                        if (count($result)){
                            foreach ($result as $k => $v){
                                ?>
                                <tr>
                                    <td>
                                        <a href="<?= $this->url->get(["for" => "edit-post", "id" => $v->ID]); ?>"><?= $v->post_title ?></a>
                                        <?php if ($v->post_status == 'draft') echo ' — 草稿';
                                        elseif($v->post_status == 'auto-draft') echo ' — 自动草稿'; ?>
                                    </td>
                                    <td><?= $v->display_name ?></td>
                                    <td><?= $str[$k]['cateStr'] ?></td>
                                    <td><?= $str[$k]['tagStr'] ?></td>
                                    <td><?php
                                        if ($v->comment_count >0){
                                            echo $v->comment_count.' <a href=""><i class="fa fa-commenting"></i></a>';
                                        }else{
                                            echo $v->comment_count;
                                        }
                                        ?>
                                    </td>
                                    <td><?= $v->post_date ?></td>
                                    <td><?= $v->view_count ?></td>
                                    <td>
                                        <a href="<?= $this->url->get(["for" => "edit-post", "id" => $v->ID]); ?>" class="btn btn-xs bg-purple"><i class="fa fa-edit"></i> 编辑</a>
                                        <a class="btn btn-xs btn-danger"><i class="fa fa-trash-o"></i> 移到回收站</a>
                                    </td>
                                </tr>
                                <?php
                            }
                        }else{ ?>
                            <tr>
                                <td colspan="8" class="text-center">无</td>
                            </tr>
                        <?php } ?>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>标题</th>
                                <th>作者</th>
                                <th>分类目录</th>
                                <th>标签</th>
                                <th>评论</th>
                                <th>日期</th>
                                <th>阅读量</th>
                                <th>操作</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>

                <div class="box-footer clearfix">
                    <?php if ($pager->haveToPaginate()){
                        echo $pager->getLayout();
                    } ?>
                </div>
            </div>
        </div>
    </div>

</section>
