<!-- 页头 -->
<section class="content-header">
    <div class="msgTip col-md-12">
        <div class="row">
            <?php $this->flash->output(); ?>
        </div>
    </div>
    <h1>
        文章列表
    </h1>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <form action="<?= $this->url->get(""); ?>" method="POST">
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-12">
                                    <span class="input-group">
                                        <a href="">全部</a> |
                                        <a href="">已发布</a> |
                                        <a href="">草稿</a> |
                                        <a href="">回收站</a>
                                    </span>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-xs-2">
                                    <div class="input-group">
                                        <select class="form-control">
                                                <option>批量操作</option>
                                                <option>移至回收站</option>
                                        </select>
                                        <div class="input-group-btn">
                                            <button id="add-new-event" type="button" class="btn btn-default btn-flat">应用</button>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-xs-3">
                                    <div class="input-group">
                                        <span class="input-group-addon">分类</span>
                                        <select class="form-control">
                                            <option>1231231231</option>
                                        </select>
                                        <div class="input-group-btn">
                                            <button id="add-new-event" type="button" class="btn btn-default btn-flat">筛选</button>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-xs-2">
                                    <div class="input-group">
                                        <input type="text" name="user_search" class="form-control pull-right" placeholder="搜索" value="">

                                        <div class="input-group-btn">
                                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
               
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>标题</th>
                                <th>作者</th>
                                <th>分类目录</th>
                                <th>标签</th>
                                <th>评论</th>
                                <th>日期</th>
                                <th>阅读量</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Other browsers</td>
                                <td>All others</td>
                                <td>-</td>
                                <td>-</td>
                                <td>U</td>
                                <td>U</td>
                                <td>U</td>
                                <td>U</td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>标题</th>
                                <th>作者</th>
                                <th>分类目录</th>
                                <th>标签</th>
                                <th>评论</th>
                                <th>日期</th>
                                <th>阅读量</th>
                                <th>操作</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>

</section>
