<!-- 页头 -->
<section class="content-header">
    <div class="msgTip col-md-12">
        <div class="row">
            <?php $this->flash->output(); ?>
        </div>
    </div>
    <h1>
        <?= $topTitle ?>
        <small><?= $topSubtitle ?></small>
    </h1>
</section>

<!-- 主内容 -->
<section class="content">
    <div class="row">
        <div class="col-md-4">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">添加新的分类目录</h3>
                </div>

                <form class="form-horizontal" action="<?= $this->url->get("admin/user/save"); ?>" method="post">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="inputUser" class="col-sm-3 control-label">名称</label>
                            <div class="col-sm-9">
                                <input type="text" name="inputUser" class="form-control" id="inputUser" placeholder="名称">
                                <span class="help-block">目录是在站点上显示的名字。</span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputEmail" class="col-sm-3 control-label">别名</label>
                            <div class="col-sm-9">
                                <input type="email" name="inputEmail" class="form-control" id="inputEmail" placeholder="别名">
                                <span class="help-block">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">父级分类目录</label>
                            <div class="col-sm-9">
                                <select class="form-control" name="inputRole">
                                    <option value="subscriber">订阅者</option>
                                     <option value="writer">作者</option>
                                    <option value="editor">编辑</option>
                                    <option value="administrator">管理员</option>
                                </select>
                                <span class="help-block">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="desc" class="col-sm-3 control-label">描述</label>

                            <div class="col-sm-9">
                                <textarea class="form-control" id="desc" rows="3" placeholder="写一点东西吧..." name="description"></textarea>
                                <span class="help-block">关于该目录的描述。</span>
                            </div>
                        </div>
                    </div>

                    <div class="box-footer">
                        <button type="submit" class="btn btn-info pull-right">确定</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-8">

        </div>
    </div>
</section>