<!-- 页头 -->
<section class="content-header">
    <div class="msgTip col-md-12">
        <div class="row">
            <?php $this->flash->output(); ?>
        </div>
    </div>
    <h1>
        <?= $topTitle ?>
        <small><?= $topSubtitle ?></small>
    </h1>
</section>

<!-- 主内容 -->
<section class="content">
    <div class="row">
        <?php if ($type == 'category'){?>
            <div class="col-md-4">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">添加新的分类目录</h3>
                    </div>

                    <form class="form-horizontal" action="<?= $this->url->get(["for" => "new-taxonomy","type" => $type]); ?>" method="post">
                        <div class="box-body">
                            <div class="form-group">
                                <label for="inputUser" class="col-sm-3 control-label">名称</label>
                                <div class="col-sm-9">
                                    <input type="text" name="name" class="form-control" id="name" placeholder="名称">
                                    <span class="help-block">名称是在站点上显示的名字。</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail" class="col-sm-3 control-label">别名</label>
                                <div class="col-sm-9">
                                    <input type="text" name="slug" class="form-control" id="slug" placeholder="别名">
                                    <span class="help-block">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">父级分类目录</label>
                                <div class="col-sm-9">
                                    <select class="form-control" name="parent">
                                        <?= $categoryTree ?>
                                    </select>
                                    <span class="help-block">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="desc" class="col-sm-3 control-label">描述</label>
                                <div class="col-sm-9">
                                    <textarea class="form-control" id="desc" rows="3" placeholder="写一点东西吧..." name="description"></textarea>
                                    <span class="help-block">关于该分类目录的描述。</span>
                                </div>
                            </div>
                        </div>

                        <div class="box-footer">
                            <button type="submit" class="btn btn-info pull-right">确定</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-md-8">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">分类列表</h3>
                    </div>

                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>名称</th>
                                <th>描述</th>
                                <th>别名</th>
                                <th>总数</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if (count($pager) == 0){?>
                                <tr align="center">
                                    <td colspan="4" > 暂无数据 </td>
                                </tr>
                            <?php }else{
                                foreach ($pager->getIterator() as $item){?>
                                    <tr>
                                        <td><?= $item['name'] ?></td>
                                        <td><?= $item['description'] ?></td>
                                        <td><?= $item['slug'] ?></td>
                                        <td><?= $item['count'] ?></td>
                                    </tr>
                                    <?php
                                }
                            }
                            ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>名称</th>
                                <th>描述</th>
                                <th>别名</th>
                                <th>总数</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>

                    <div class="box-footer clearfix">
                        <?php
                        if ($pager->haveToPaginate()){
                            echo $pager->getLayout();
                        }
                        ?>
                    </div>
                </div>
            </div>
        <?} elseif($type == 'tag'){?>
            <div class="col-md-4">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">添加新的标签</h3>
                    </div>

                    <form class="form-horizontal" action="<?= $this->url->get(["for" => "new-taxonomy","type" => $type]); ?>" method="post">
                        <div class="box-body">
                            <div class="form-group">
                                <label for="inputUser" class="col-sm-2 control-label">名称</label>
                                <div class="col-sm-10">
                                    <input type="text" name="name" class="form-control" id="name" placeholder="名称">
                                    <span class="help-block">名称是在站点上显示的名字。</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail" class="col-sm-2 control-label">别名</label>
                                <div class="col-sm-10">
                                    <input type="text" name="slug" class="form-control" id="slug" placeholder="别名">
                                    <span class="help-block">“别名”是在URL中使用的别称，它可以令URL更美观。通常使用小写，只能包含字母，数字和连字符（-）。</span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="desc" class="col-sm-2 control-label">描述</label>
                                <div class="col-sm-10">
                                    <textarea class="form-control" id="desc" rows="3" placeholder="写一点东西吧..." name="description"></textarea>
                                    <span class="help-block">关于该标签的描述。</span>
                                </div>
                            </div>
                        </div>

                        <div class="box-footer">
                            <button type="submit" class="btn btn-info pull-right">确定</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-md-8">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">标签列表</h3>
                    </div>

                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>名称</th>
                                <th>描述</th>
                                <th>别名</th>
                                <th>总数</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php if (count($pager) == 0){?>
                                <tr align="center">
                                    <td colspan="4" > 暂无数据 </td>
                                </tr>
                            <?php }else{
                                foreach ($pager->getIterator() as $item){?>
                                    <tr>
                                        <td><?= $item['name'] ?></td>
                                        <td><?= $item['description'] ?></td>
                                        <td><?= $item['slug'] ?></td>
                                        <td><?= $item['count'] ?></td>
                                    </tr>
                                    <?php
                                }
                            }
                            ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th>名称</th>
                                <th>描述</th>
                                <th>别名</th>
                                <th>总数</th>
                            </tr>
                            </tfoot>
                        </table>
                    </div>

                    <div class="box-footer clearfix">
                        <?php
                        if ($pager->haveToPaginate()){
                            echo $pager->getLayout();
                        }
                        ?>
                    </div>
                </div>
            </div>
        <?} ?>
    </div>
</section>