<div class="card">
    <div class="card-header">
        <h4><i class="fa fa-file-o"></i> 归档</h4>
    </div>

    <?php
    if ($list){ ?>
    <ul class="list-group" id="archives">
        <?php foreach ($list as $yearKey => $year){ ?>
            <li class="list-group-item border-0">
                <h4 class="mb-2"><?= $yearKey ?> 年</h4>
                <ul class="list-group p-1">
                    <?php foreach ($year as $monthKey => $month){ ?>
                        <li class="list-group-item archive-month border border-1">
                            <h5><?= $monthKey ?> 月<small class="float-right text-muted"><?= count($month) ?> 篇文章</small></h5>
                            <ul class="list-group list-group-flush month_items">
                                <?php foreach ($month as $day) { ?>
                                    <li class="list-group-item">
                                        <?= $day['theDay'] ?> 日：<a href="<?= $day['guid'] ?>"><?= $day['post_title'] ?></a>
                                        <span class="badge badge-primary d-flex float-right"><?= $day['comment_count'] ?></span>
                                    </li>
                                <?php } ?>
                            </ul>
                        </li>
                    <?php } ?>
                </ul>
            </li>
        <?php } ?>
    </ul>
    <?php }else{ ?>
        <div class="card-body">
            暂无文章
        </div>
    <?php } ?>

</div>
