<div class="row post-container bg-white no-gutters mb-3">
    <div class="col-12 post-header">
        <h1 class="post-title">Guzzle：PHP的HTTP客户端</h1>
    </div>

    <div class="col-12 post_meta">
        <ul class="post_meta_ul list-unstyled">
            <li class="inline-li float-left mr-2">
                <i class="fa fa-calendar-check-o"></i>
                2017-07-31 16:09
            </li>
        </ul>
    </div>

    <div id="editormd-view" class="col-12 post-content editormd">
        <div class="editormd-html-textarea markdown-body" name="editormd-view-html-code"><?= $content ?></div>
    </div>
</div>