<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>瓜子皮 - Goozp's Blog</title>
    <?php
    /* HTML 头部资源 */
    echo $this->tag->stylesheetLink("themes/default/public/library/bootstrap/css/bootstrap.min.css"); // Bootstrap
    echo $this->tag->stylesheetLink("themes/default/public/css/globals.css");
    ?>
</head>
<body
    <div class="container-fluid">
        <div class="row">
            <div class="author col-sm-12 col-md-2 ">
                <?php $this->partial("shared/author"); ?>
            </div>

            <div class="right col-sm-12 ml-sm-auto col-md-10" role="main">
                <div class="row">
                    <div class="right-top col-sm-12">
                        <div class="col-sm-12 no-gutters bg-primary text-white sticky-top">
                            <a href="#">全部</a>
                            <a href="#">PHP</a>
                            <a href="#">前端</a>
                            <a href="#">后端</a>
                            <a href="#">Git</a>
                            <a href="#">Linux</a>
                        </div>
                    </div>

                    <div class="content col-sm-10">
                        <?php echo $this->getContent(); ?>
                    </div>

                    <div class="content col-sm-2">
                    </div>

                    <footer class="footer col-sm-12">
                        <?php $this->partial("shared/footer"); ?>
                    </footer>
                </div>
            </div>
        </div>
    </div>

    <?php
        /* HTML尾部资源 */
        echo $this->tag->javascriptInclude("themes/default/public/js/vendor/jquery-slim.min.js");
        echo $this->tag->javascriptInclude("themes/default/public/js/vendor/popper.min.js");
        echo $this->tag->javascriptInclude("themes/default/public/library/bootstrap/js/bootstrap.min.js");
        echo $this->tag->javascriptInclude("themes/default/public/js/ie10-viewport-bug-workaround.js");
    ?>
</body>
</html>
