<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <!-- title -->
    <?php echo $this->tag->getTitle(); ?>

    <?php
    /* HTML 头部资源 */
    echo $this->tag->stylesheetLink("themes/default/public/library/bootstrap/css/bootstrap.min.css"); // Bootstrap
    echo $this->tag->stylesheetLink("themes/default/public/library/font-awesome-4.7.0/css/font-awesome.min.css"); // Bootstrap
    echo $this->tag->stylesheetLink("themes/default/public/css/globals.css");
    ?>
</head>
<body>
    <div class="container-fluid">
        <!-- 加载header -->
        <div class="top col-md-auto">
            <?php $this->partial("shared/header"); ?>
        </div>

        <!-- 加载common模块 -->
        <div class="content">
            <?php echo $this->getContent(); ?>
        </div>

        <!-- 加载footer -->
        <footer class="footer col-12">
            <?php $this->partial("shared/footer"); ?>
        </footer>
    </div>

    <?php
        /* HTML尾部资源 */
        echo $this->tag->javascriptInclude("themes/default/public/js/vendor/jquery-slim.min.js");
        echo $this->tag->javascriptInclude("themes/default/public/js/vendor/popper.min.js");
        echo $this->tag->javascriptInclude("themes/default/public/library/bootstrap/js/bootstrap.min.js");
        echo $this->tag->javascriptInclude("themes/default/public/js/ie10-viewport-bug-workaround.js");
    ?>
</body>
</html>
