<!-- 页头 -->
<section class="content-header">
    <div class="msgTip col-md-12">
        <div class="row">
            <?php $this->flash->output(); ?>
        </div>
    </div>
    <h1>
        讨论设置
        <small>评论、评论展示相关配置</small>
    </h1>
</section>

<!-- 主内容 -->
<section class="content">
    <div class="box box-default  box-solid">
        <form class="form-horizontal">
            <div class="box-body">
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">是否开启评论</label>

                    <div class="col-sm-4">
                        <div class="checkbox">
                            <label><input type="checkbox">文章</label>&nbsp;&nbsp;&nbsp;&nbsp;
                            <label><input type="checkbox">页面</label>
                            <span class="help-block">开启评论功能让用户进行评论。</span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">评论设置</label>

                    <div class="col-sm-4">
                        <div class="row">
                            <div class="checkbox">
                                <div class="col-sm-12">
                                    <label><input type="checkbox">用户必须注册并登录才可以发表评论</label>
                                </div>
                                <div class="col-sm-12">
                                    <label>
                                        <input type="checkbox">分页显示评论，
                                    </label>
                                    每页显示
                                    <select name="">
                                        <option value="" >5</option>
                                        <option value="" >10</option>
                                        <option value="" >15</option>
                                        <option value="" >20</option>
                                        <option value="" >25</option>
                                    </select>
                                    条评论，默认显示
                                    <select name="">
                                        <option value="" >最后</option>
                                        <option value="" >最前</option>
                                    </select>
                                    一页
                                </div>
                                <div class="col-sm-12">
                                    在每个页面顶部显示
                                    <select name="">
                                        <option value="" >旧的</option>
                                        <option value="" >新的</option>
                                    </select>
                                    评论
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">在评论显示之前</label>

                    <div class="col-sm-4">
                        <div class="checkbox">
                            <label><input type="checkbox">评论必须经人工批准</label>&nbsp;&nbsp;&nbsp;&nbsp;
                            <label><input type="checkbox">评论者先前须有评论通过了审核</label>
                            <span class="help-block">评论展示条件。</span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <h4 class="col-sm-2 control-label"><b>头像</b></h4>
                </div>

                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">头像显示</label>

                    <div class="col-sm-4">
                        <div class="checkbox">
                            <label><input type="checkbox">显示头像</label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <button type="submit" class="btn bg-purple col-sm-offset-2">保存更改</button>
            </div>
        </form>
    </div>
</section>

