<!-- 页头 -->
<section class="content-header">
    <div class="msgTip col-md-12">
        <div class="row">
            <?php $this->flash->output(); ?>
        </div>
    </div>
    <h1>
        讨论设置
        <small>评论、评论展示相关配置</small>
    </h1>
</section>

<!-- 主内容 -->
<section class="content">
    <div class="box box-default  box-solid">
        <form class="form-horizontal" action="<?= $this->url->get("admin/setting/saveDiscuss"); ?>" method="post">
            <div class="box-body">
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">是否开启评论</label>

                    <div class="col-sm-4">
                        <div class="checkbox">
                            <label><input type="checkbox" name="post_comment_status" value="1" <?php if($post_comment_status == 'open') echo 'checked' ?>>文章</label>&nbsp;&nbsp;&nbsp;&nbsp;
                            <label><input type="checkbox" name="page_comment_status" value="1" <?php if($page_comment_status == 'open') echo 'checked' ?>>页面</label>
                            <span class="help-block">开启评论功能让用户进行评论。</span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">评论设置</label>

                    <div class="col-sm-4">
                        <div class="row">
                            <div class="checkbox">
                                <div class="col-sm-12">
                                    <label><input name="comment_need_register" value="1" type="checkbox" <?php if ($comment_need_register == 1) echo 'checked' ?>>用户必须注册并登录才可以发表评论</label>
                                </div>
                                <div class="col-sm-12">
                                    <label>
                                        <input name="show_comment_page" value="1" type="checkbox" <?php if ($show_comment_page == 1) echo 'checked' ?>>分页显示评论，
                                    </label>
                                    每页显示
                                    <select name="comment_per_page">
                                        <option value="5" <?php if ($comment_per_page == 5) echo 'selected' ?>>5</option>
                                        <option value="10" <?php if ($comment_per_page == 10) echo 'selected' ?>>10</option>
                                        <option value="15" <?php if ($comment_per_page == 15) echo 'selected' ?>>15</option>
                                        <option value="20" <?php if ($comment_per_page == 20) echo 'selected' ?>>20</option>
                                        <option value="25" <?php if ($comment_per_page == 25) echo 'selected' ?>>25</option>
                                    </select>
                                    条评论，默认显示
                                    <select name="comment_page_first">
                                        <option value="last" <?php if ($comment_page_first == 'last') echo 'selected' ?> >最后</option>
                                        <option value="front" <?php if ($comment_page_first == 'front') echo 'selected' ?> >最前</option>
                                    </select>
                                    一页
                                </div>
                                <div class="col-sm-12">
                                    在每个页面顶部显示
                                    <select name="comment_page_top">
                                        <option value="old" <?php if ($comment_page_top == 'old') echo 'selected' ?> >旧的</option>
                                        <option value="new" <?php if ($comment_page_top == 'new') echo 'selected' ?> >新的</option>
                                    </select>
                                    评论
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">在评论显示之前</label>

                    <div class="col-sm-4">
                        <label><input name="comment_before_show" value="must_approve" type="radio" <?php if ($comment_before_show == 'must_approve') echo 'checked' ?>>评论必须经人工批准</label>&nbsp;&nbsp;&nbsp;&nbsp;
                        <label><input name="comment_before_show" value="approve_before"  type="radio" <?php if ($comment_before_show == 'approve_before') echo 'checked' ?>>评论者先前须有评论通过了审核</label>
                        <label><input name="comment_before_show" value="directly"  type="radio" <?php if ($comment_before_show == 'directly') echo 'checked' ?>>直接显示</label>
                        <span class="help-block">评论展示条件。</span>
                    </div>
                </div>

                <div class="form-group">
                    <h4 class="col-sm-2 control-label"><b>头像</b></h4>
                </div>

                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">头像显示</label>

                    <div class="col-sm-4">
                        <div class="checkbox">
                            <label><input name="show_avatar" type="checkbox" value="1" <?php if ($show_avatar == 1) echo 'checked' ?>>显示头像</label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <button type="submit" class="btn bg-purple col-sm-offset-2">保存更改</button>
            </div>
        </form>
    </div>
</section>

