<!-- 页头 -->
<section class="content-header">
    <div class="msgTip col-md-12">
        <div class="row">
            <?php $this->flash->output(); ?>
        </div>
    </div>
    <h1>
        阅读设置
        <small>文章展示、抓取相关配置</small>
    </h1>
</section>

<!-- 主内容 -->
<section class="content">
    <div class="box box-default  box-solid">
        <form class="form-horizontal">
            <div class="box-body">
                <div class="form-group">
                    <label for="site_name" class="col-sm-2 control-label">首页显示</label>

                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="site_name" placeholder="输入站点标题">
                        <span class="help-block">即站点的名称</span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">首页显示</label>

                    <div class="col-sm-4">
                        <div class="radio">
                            <label><input type="radio">是</label>&nbsp;&nbsp;&nbsp;&nbsp;
                            <label><input type="radio">否</label>
                            <span class="help-block">是否开放站点的注册功能。</span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">启用 XML 站点地图</label>

                    <div class="col-sm-4">
                        <div class="checkbox">
                            <label><input type="checkbox">是</label>&nbsp;&nbsp;&nbsp;&nbsp;
                            <label><input type="checkbox">否</label>
                            <span class="help-block">是否开放站点的注册功能。</span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="box-footer">
                <button type="submit" class="btn bg-purple col-sm-offset-2">保存更改</button>
            </div>
        </form>
    </div>
</section>

