<nav aria-label="breadcrumb" role="navigation">
    <ol class="breadcrumb bg-light">
        <li class="breadcrumb-item"><a href="#">专题</a></li>
        <li class="breadcrumb-item"><a href="#">PHP</a></li>
        <li class="breadcrumb-item active" aria-current="page">Phalcon</li>
    </ol>
</nav>

<div class="alert alert-light" role="alert">
    <h4 class="alert-heading"><?= $subjectName ?></h4>
    <p><?= $subjectDescription ?></p>
    <hr>
    <p class="mb-0">当前共有 <?= $total ?> 篇文章</p>
</div>

<div class="list-group">
    <?php foreach ($posts as $post){ ?>
        <a href="<?= $post['guid'] ?>" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1"><?= $post['post_title'] ?></h5>
                <small><?= date('Y-m-d H:i', strtotime($post['post_date'])); ?></small>
            </div>
            <p class="mb-1"><?= articleExcerpt($post['post_html_content'], 150) ?></p>
            <small><?= $post['view_count'] ?> 阅读，<?= $post['comment_count'] ?> 评论</small>
        </a>
    <?php } ?>
</div>