<nav aria-label="breadcrumb" role="navigation">
    <ol class="breadcrumb bg-light">
        <li class="breadcrumb-item"><a href="#">专题</a></li>
        <li class="breadcrumb-item"><a href="#">PHP</a></li>
        <li class="breadcrumb-item active" aria-current="page">Phalcon</li>
    </ol>
</nav>

<div class="subject-body card-columns">
    <div class="card">
        <a href=""><?php echo $this->tag->image([
            "themes/default/public/images/phplogo.png",
            "class"=>"card-img-top",
            "alt" => "Card image cap",
            "width" => 300,
            "height" => 180,
        ]);?></a>
        <div class="card-body">
            <h4 class="card-title"><a href="">PHP</a></h4>
            <p class="card-text">PHP（外文名:PHP: Hypertext Preprocessor，中文名：“超文本预处理器”）是一种通用开源脚本语言。</p>
            <a href="#" class="card-button btn btn-sm btn-primary">前往</a>
        </div>
        <div class="card-footer text-muted">
             上一次更新于 3分钟前
        </div>
    </div>

    <div class="card">
        <a href=""><?php echo $this->tag->image([
                "themes/default/public/images/phplogo.png",
                "class"=>"card-img-top",
                "alt" => "Card image cap",
                "width" => 300,
                "height" => 180,
            ]);?></a>
        <div class="card-body">
            <h4 class="card-title"><a href="">PHP</a></h4>
            <p class="card-text">PHP（外文名:PHP: Hypertext Preprocessor，中文名：“超文本预处理器”）是一种通用开源脚本语言。语法吸收了C语言、Java和Perl的特点，利于学习，使用广泛，主要适用于Web开发领域。PHP 独特的语法混合了C、Java、Perl以及PHP自创的语法。</p>
            <a href="#" class="card-button btn btn-sm btn-primary">前往</a>
        </div>
        <div class="card-footer text-muted">
            上一次更新于 3分钟前
        </div>
    </div>
</div>