<div class="text-center">
    <img src="https://www.gzpblog.com/wp-content/themes/SaltedFish/public/images/jumbotron_self.png"
         class="rounded-circle border border-light" alt="..." width="s150" height="150">
    <div class="author-name">
        <p><strong>Goozp</strong></p>
    </div>
    <div class="author-word">
        <p>奋斗的扫地工</p>
    </div>
</div>

<nav class="author-nav nav flex-column text-center">
    <a class="nav-link active" href="#">首页</a>
    <a class="nav-link" href="#">作品</a>
    <a class="nav-link" href="#">归档</a>
    <a class="nav-link" href="#">友链</a>
    <a class="nav-link" href="#">关于</a>
</nav>

<div class="author-word ">
    <p>“当你发现自己的才华撑不起野心时，就请安静下来学习吧。”</p>
</div>