<div class="container">
    <div class="text-center">
        <p>
            Copyright © 2017 <a id="" href="http://www.goozp.com" target="_blank">goozp</a> All Rights Reserved.
            Powered by <a href="https://www.gzpblog.com" target="_blank" rel="nofollow">zPhal</a>
        </p>
        <p>
            <a href="http://www.miitbeian.gov.cn/" target="_blank" rel="nofollow">粤ICP备16013442号</a>
            &nbsp|&nbsp
            <a href="/sitemap.xml" target="_blank">网站地图</a>
            &nbsp|&nbsp
            本站运行于 阿里云
        </p>
    </div>
</div>