<div class="sidebar top-sidebar">
    <div class="widget">
        111
    </div>
</div>

<div class="sidebar sticky-sidebar">
    <div class="widget">
        222
    </div>

    <div class="widget widget-tagsMenu clearfix visible-lg-block">
        <h4><span><i class="fa fa-tags"></i>&nbsp;分类</span></h4>
        <ul id="menu-%e4%be%a7%e6%a0%8f%e6%a0%87%e7%ad%be%e5%8c%96%e8%8f%9c%e5%8d%95" class="menu"><li id="menu-item-944" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-944"><a href="https://www.gzpblog.com/category/essay/essay-me">个人随笔</a></li>
            <li id="menu-item-945" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-945"><a href="https://www.gzpblog.com/category/essay/essay-extra">发发牢骚</a></li>
            <li id="menu-item-946" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-946"><a href="https://www.gzpblog.com/category/essay/essay-life">生活杂谈</a></li>
            <li id="menu-item-947" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-947"><a href="https://www.gzpblog.com/category/code/code-about/php">PHP</a>
                <ul class="sub-menu">
                    <li id="menu-item-1172" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1172"><a href="https://www.gzpblog.com/category/code/library-expand/swoole">Swoole</a></li>
                    <li id="menu-item-961" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-961"><a href="https://www.gzpblog.com/category/code/framework/thinkphp">ThinkPHP</a></li>
                    <li id="menu-item-1170" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1170"><a href="https://www.gzpblog.com/category/code/framework/workerman">Workerman</a></li>
                    <li id="menu-item-960" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-960"><a href="https://www.gzpblog.com/category/code/framework/phalcon">Phalcon</a></li>
                    <li id="menu-item-965" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-965"><a href="https://www.gzpblog.com/category/code/code-software/wordpress">WordPress</a></li>
                    <li id="menu-item-963" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-963"><a href="https://www.gzpblog.com/category/code/code-software/ecshop">ECshop</a></li>
                    <li id="menu-item-959" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-959"><a href="https://www.gzpblog.com/category/code/framework/phalapi">PhalApi</a></li>
                    <li id="menu-item-964" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-964"><a href="https://www.gzpblog.com/category/code/code-software/typecho">Typecho</a></li>
                </ul>
            </li>
            <li id="menu-item-948" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-948"><a href="https://www.gzpblog.com/category/code/code-about/javascript">JavaScript</a>
                <ul class="sub-menu">
                    <li id="menu-item-956" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-956"><a href="https://www.gzpblog.com/category/code/library-expand/jquery">JQuery</a></li>
                    <li id="menu-item-962" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-962"><a href="https://www.gzpblog.com/category/code/framework/vue-js">Vue.js</a></li>
                    <li id="menu-item-958" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-958"><a href="https://www.gzpblog.com/category/code/othertechnology/ajax">ajax</a></li>
                </ul>
            </li>
            <li id="menu-item-1014" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1014"><a href="https://www.gzpblog.com/category/code/code-about/python">Python</a></li>
            <li id="menu-item-949" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-949"><a href="https://www.gzpblog.com/category/code/code-about/go">Go</a></li>
            <li id="menu-item-952" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-952"><a href="https://www.gzpblog.com/category/code/systemoperation/linux">Linux</a></li>
            <li id="menu-item-1026" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-1026"><a href="https://www.gzpblog.com/category/code/systemoperation/docker">Docker</a></li>
            <li id="menu-item-951" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-951"><a href="https://www.gzpblog.com/category/code/systemoperation/apache">Apache</a></li>
            <li id="menu-item-953" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-953"><a href="https://www.gzpblog.com/category/code/systemoperation/nginx">Nginx</a></li>
            <li id="menu-item-954" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-954"><a href="https://www.gzpblog.com/category/code/sql/mysql">MySQL</a></li>
            <li id="menu-item-957" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-957"><a href="https://www.gzpblog.com/category/code/library-expand/memcache">Memcache</a></li>
            <li id="menu-item-955" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-955"><a href="https://www.gzpblog.com/category/code/sql/redis">Redis</a></li>
            <li id="menu-item-966" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-966"><a href="https://www.gzpblog.com/category/code/front-about">前端综合</a></li>
            <li id="menu-item-967" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-967"><a href="https://www.gzpblog.com/category/code/back-about">后端综合</a></li>
            <li id="menu-item-968" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-968"><a href="https://www.gzpblog.com/category/code/code-learning">学习笔记</a></li>
        </ul>        </div>

    <div class="widget widget-news visible-lg-block">
        <h4><span><i class="fa fa-leaf"></i>&nbsp;最新文章</span></h4>
        <ul class="list fa-ul">
            <li class="widget-new"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20171014/1225.html" title="emmmmm..好久没更新了">emmmmm..好久没更新了</a>
                </p>
            </li>
            <li class="widget-new"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170801/1186.html" title="火狐浏览器X-Content-Type-Options导致Images类型无法加载">火狐浏览器X-Content-Type-Options导致Images类型无法加载</a>
                </p>
            </li>
            <li class="widget-new"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170731/1175.html" title="Guzzle：PHP的HTTP客户端">Guzzle：PHP的HTTP客户端</a>
                </p>
            </li>
            <li class="widget-new"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170720/1166.html" title="用Workerman快速实现Socket服务">用Workerman快速实现Socket服务</a>
                </p>
            </li>
            <li class="widget-new"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170718/1161.html" title="「PSR 规范」关于PHP标准规范">「PSR 规范」关于PHP标准规范</a>
                </p>
            </li>
            <li class="widget-new"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170718/1151.html" title="消息队列及PHP中的简单实现与应用">消息队列及PHP中的简单实现与应用</a>
                </p>
            </li>
        </ul>
    </div>

    <div class="widget widget-comments visible-lg-block">
        <h4><span><i class="fa fa-comments"></i>&nbsp;最新评论</span></h4>
        <ul>
            <li>
                <div class="col-xs-12 col-sm-2 gavatar"><img alt="forever0121" src="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=86&amp;r=g 2x" class="avatar avatar-43 photo img-responsive img-circle" width="43" height="43"></div>
                <div class="col-xs-12 col-sm-10 comments-con">
                    <p class="comments-name"><a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">forever0121</a>
                        <span class="comments-time">2017-12-04</span>
                    </p>
                    <p class="comments-comment"><a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">请问博主为什么我输入docker-compose -version会报错，报错信息UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)
                            Failed to execute script docker-compose</a></p>
                </div>
            </li><li>
                <div class="col-xs-12 col-sm-2 gavatar"><img alt="小黄" src="https://secure.gravatar.com/avatar/ebf1922906b6ddc111927a26ef845047?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/ebf1922906b6ddc111927a26ef845047?s=86&amp;r=g 2x" class="avatar avatar-43 photo img-responsive img-circle" width="43" height="43"></div>
                <div class="col-xs-12 col-sm-10 comments-con">
                    <p class="comments-name"><a href="https://www.gzpblog.com/20161230/561.html#comment-3922">小黄</a>
                        <span class="comments-time">2017-11-27</span>
                    </p>
                    <p class="comments-comment"><a href="https://www.gzpblog.com/20161230/561.html#comment-3922">非常感谢</a></p>
                </div>
            </li><li>
                <div class="col-xs-12 col-sm-2 gavatar"><img alt="小黄" src="https://secure.gravatar.com/avatar/ebf1922906b6ddc111927a26ef845047?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/ebf1922906b6ddc111927a26ef845047?s=86&amp;r=g 2x" class="avatar avatar-43 photo img-responsive img-circle" width="43" height="43"></div>
                <div class="col-xs-12 col-sm-10 comments-con">
                    <p class="comments-name"><a href="https://www.gzpblog.com/20161230/561.html#comment-3745">小黄</a>
                        <span class="comments-time">2017-11-24</span>
                    </p>
                    <p class="comments-comment"><a href="https://www.gzpblog.com/20161230/561.html#comment-3745">这个curl让我知道了啥叫规范，我立马支持了一点点小心意，能不能把cURLError.php也告诉我让我学习啊大神</a></p>
                </div>
            </li><li>
                <div class="col-xs-12 col-sm-2 gavatar"><img alt="新闻头条" src="https://secure.gravatar.com/avatar/89ef996d6fba902b3cb5a349548fa781?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/89ef996d6fba902b3cb5a349548fa781?s=86&amp;r=g 2x" class="avatar avatar-43 photo img-responsive img-circle" width="43" height="43"></div>
                <div class="col-xs-12 col-sm-10 comments-con">
                    <p class="comments-name"><a href="https://www.gzpblog.com/20170221/685.html#comment-2768">新闻头条</a>
                        <span class="comments-time">2017-11-08</span>
                    </p>
                    <p class="comments-comment"><a href="https://www.gzpblog.com/20170221/685.html#comment-2768">文章不错非常喜欢</a></p>
                </div>
            </li><li>
                <div class="col-xs-12 col-sm-2 gavatar"><img alt="健康网" src="https://secure.gravatar.com/avatar/dcd3a0511f1f4076d370a38115b80e9d?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/dcd3a0511f1f4076d370a38115b80e9d?s=86&amp;r=g 2x" class="avatar avatar-43 photo img-responsive img-circle" width="43" height="43"></div>
                <div class="col-xs-12 col-sm-10 comments-con">
                    <p class="comments-name"><a href="https://www.gzpblog.com/20171014/1225.html#comment-2073">健康网</a>
                        <span class="comments-time">2017-10-25</span>
                    </p>
                    <p class="comments-comment"><a href="https://www.gzpblog.com/20171014/1225.html#comment-2073">学海无涯，博客有道！拜读咯！</a></p>
                </div>
            </li>
        </ul>
    </div>
</div>