<div class="row">
    <div class="sidebar-tags col-12 mt-3 bg-white">
        <button type="button" class="btn btn-outline-primary btn-sm">Primary</button>
        <button type="button" class="btn btn-outline-secondary  btn-sm">Secondary</button>
        <button type="button" class="btn btn-outline-success  btn-sm">Success</button>
        <button type="button" class="btn btn-outline-danger btn-sm">Danger</button>
        <button type="button" class="btn btn-outline-warning btn-sm">Warning</button>
        <button type="button" class="btn btn-outline-info btn-sm">Info</button>
        <button type="button" class="btn btn-outline-dark btn-sm">Dark</button>
    </div>
</div>