<div class="sidebar sticky-sidebar">
    <div class="widget widget-category d-block clearfix">
        <h4><span><i class="fa fa-tags"></i>&nbsp;分类</span></h4>
        <?= $widgetCategory ?>
    </div>

    <div class="widget widget-news d-block">
        <h4><span><i class="fa fa-leaf"></i>&nbsp;最新文章</span></h4>
        <ul class="news-list fa-ul ml-4 mb-0">
            <li class="news-item"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20171014/1225.html" title="emmmmm..好久没更新了">emmmmm..好久没更新了</a>
                </p>
            </li>
            <li class="news-item"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170801/1186.html" title="火狐浏览器X-Content-Type-Options导致Images类型无法加载">火狐浏览器X-Content-Type-Options导致Images类型无法加载</a>
                </p>
            </li>
            <li class="news-item"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170731/1175.html" title="Guzzle：PHP的HTTP客户端">Guzzle：PHP的HTTP客户端</a>
                </p>
            </li>
            <li class="news-item"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170720/1166.html" title="用Workerman快速实现Socket服务">用Workerman快速实现Socket服务</a>
                </p>
            </li>
            <li class="news-item"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170718/1161.html" title="「PSR 规范」关于PHP标准规范">「PSR 规范」关于PHP标准规范</a>
                </p>
            </li>
            <li class="news-item"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170718/1151.html" title="消息队列及PHP中的简单实现与应用">消息队列及PHP中的简单实现与应用</a>
                </p>
            </li>
        </ul>
    </div>

    <div class="widget widget-comments d-block clearfix">
        <h4><span><i class="fa fa-comments"></i>&nbsp;最新评论</span></h4>
        <ul class="comments-list list-unstyled m-0">
            <li class="comments-item media m-1">
                <img class="avatar avatar-43  img-fluid rounded-circle"  alt="forever0121" src="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=86&amp;r=g 2x">
                <div class="comments-body  media-body ml-2 text-truncate">
                    <p class="comments-name font-weight-bold m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">forever0121</a>
                    </p>
                    <p class="comments-comment text-truncate m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">
                            请问博主为什么我输入docker-compose -version会报错，报错信息UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)
                            Failed to execute script docker-compose
                        </a>
                    </p>
                </div>
            </li>
            <li class="comments-item media m-1">
                <img class="avatar avatar-43  img-fluid rounded-circle"  alt="forever0121" src="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=86&amp;r=g 2x">
                <div class="comments-body  media-body ml-2 text-truncate">
                    <p class="comments-name font-weight-bold m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">forever0121</a>
                    </p>
                    <p class="comments-comment text-truncate m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">
                            请问博主为什么我输入docker-compose -version会报错，报错信息UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)
                            Failed to execute script docker-compose
                        </a>
                    </p>
                </div>
            </li>
            <li class="comments-item media m-1">
                <img class="avatar avatar-43  img-fluid rounded-circle"  alt="forever0121" src="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=86&amp;r=g 2x">
                <div class="comments-body  media-body ml-2 text-truncate">
                    <p class="comments-name font-weight-bold m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">forever0121</a>
                    </p>
                    <p class="comments-comment text-truncate m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">
                            请问博主为什么我输入docker-compose -version会报错，报错信息UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)
                            Failed to execute script docker-compose
                        </a>
                    </p>
                </div>
            </li>
            <li class="comments-item media m-1">
                <img class="avatar avatar-43  img-fluid rounded-circle"  alt="forever0121" src="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=86&amp;r=g 2x">
                <div class="comments-body  media-body ml-2 text-truncate">
                    <p class="comments-name font-weight-bold m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">forever0121</a>
                    </p>
                    <p class="comments-comment text-truncate m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">
                            请问博主为什么我输入docker-compose -version会报错，报错信息UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)
                            Failed to execute script docker-compose
                        </a>
                    </p>
                </div>
            </li>
            <li class="comments-item media m-1">
                <img class="avatar avatar-43  img-fluid rounded-circle"  alt="forever0121" src="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=86&amp;r=g 2x">
                <div class="comments-body  media-body ml-2 text-truncate">
                    <p class="comments-name font-weight-bold m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">forever0121</a>
                    </p>
                    <p class="comments-comment text-truncate m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">
                            请问博主为什么我输入docker-compose -version会报错，报错信息UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)
                            Failed to execute script docker-compose
                        </a>
                    </p>
                </div>
            </li>
        </ul>
    </div>

    <div class="widget widget-static d-block">
        <h4><span><i class="fa fa-fire"></i>&nbsp;统计</span></h4>

    </div>
</div>