<div class="sidebar sticky-sidebar">
    <div class="widget widget-category d-block clearfix">
        <h4><span><i class="fa fa-tags"></i>&nbsp;分类</span></h4>
        <ul id="menu-%e4%be%a7%e6%a0%8f%e6%a0%87%e7%ad%be%e5%8c%96%e8%8f%9c%e5%8d%95" class="category-list list-unstyled"><li id="category-item-944" class="category-item category-item-type-taxonomy category-item-object-category category-item-944"><a href="https://www.gzpblog.com/category/essay/essay-me">个人随笔</a></li>
            <li id="category-item-945" class="category-item category-item-type-taxonomy category-item-object-category category-item-945"><a href="https://www.gzpblog.com/category/essay/essay-extra">发发牢骚</a></li>
            <li id="category-item-946" class="category-item category-item-type-taxonomy category-item-object-category category-item-946"><a href="https://www.gzpblog.com/category/essay/essay-life">生活杂谈</a></li>
            <li id="category-item-947" class="category-item category-item-type-taxonomy category-item-object-category category-item-has-children category-item-947"><a href="https://www.gzpblog.com/category/code/code-about/php">PHP</a>
                <ul class="category-sub-list list-unstyled">
                    <li id="category-item-1172" class="category-item category-item-type-taxonomy category-item-object-category category-item-1172"><a href="https://www.gzpblog.com/category/code/library-expand/swoole">Swoole</a></li>
                    <li id="category-item-961" class="category-item category-item-type-taxonomy category-item-object-category category-item-961"><a href="https://www.gzpblog.com/category/code/framework/thinkphp">ThinkPHP</a></li>
                    <li id="category-item-1170" class="category-item category-item-type-taxonomy category-item-object-category category-item-1170"><a href="https://www.gzpblog.com/category/code/framework/workerman">Workerman</a></li>
                    <li id="category-item-960" class="category-item category-item-type-taxonomy category-item-object-category category-item-960"><a href="https://www.gzpblog.com/category/code/framework/phalcon">Phalcon</a></li>
                    <li id="category-item-965" class="category-item category-item-type-taxonomy category-item-object-category category-item-965"><a href="https://www.gzpblog.com/category/code/code-software/wordpress">WordPress</a></li>
                    <li id="category-item-963" class="category-item category-item-type-taxonomy category-item-object-category category-item-963"><a href="https://www.gzpblog.com/category/code/code-software/ecshop">ECshop</a></li>
                    <li id="category-item-959" class="category-item category-item-type-taxonomy category-item-object-category category-item-959"><a href="https://www.gzpblog.com/category/code/framework/phalapi">PhalApi</a></li>
                    <li id="category-item-964" class="category-item category-item-type-taxonomy category-item-object-category category-item-964"><a href="https://www.gzpblog.com/category/code/code-software/typecho">Typecho</a></li>
                </ul>
            </li>
            <li id="category-item-948" class="category-item category-item-type-taxonomy category-item-object-category category-item-has-children category-item-948"><a href="https://www.gzpblog.com/category/code/code-about/javascript">JavaScript</a>
                <ul class="category-sub-list list-unstyled">
                    <li id="category-item-956" class="category-item category-item category-item-type-taxonomy category-item-object-category category-item-956"><a href="https://www.gzpblog.com/category/code/library-expand/jquery">JQuery</a></li>
                    <li id="category-item-962" class="category-item category-item-type-taxonomy category-item-object-category category-item-962"><a href="https://www.gzpblog.com/category/code/framework/vue-js">Vue.js</a></li>
                    <li id="category-item-958" class="category-item category-item-type-taxonomy category-item-object-category category-item-958"><a href="https://www.gzpblog.com/category/code/othertechnology/ajax">ajax</a></li>
                </ul>
            </li>
            <li id="category-item-1014" class="category-item category-item-type-taxonomy category-item-object-category category-item-1014"><a href="https://www.gzpblog.com/category/code/code-about/python">Python</a></li>
            <li id="category-item-949" class="category-item category-item-type-taxonomy category-item-object-category category-item-949"><a href="https://www.gzpblog.com/category/code/code-about/go">Go</a></li>
            <li id="category-item-952" class="category-item category-item-type-taxonomy category-item-object-category category-item-952"><a href="https://www.gzpblog.com/category/code/systemoperation/linux">Linux</a></li>
            <li id="category-item-1026" class="category-item category-item-type-taxonomy category-item-object-category category-item-1026"><a href="https://www.gzpblog.com/category/code/systemoperation/docker">Docker</a></li>
            <li id="category-item-951" class="category-item category-item-type-taxonomy category-item-object-category category-item-951"><a href="https://www.gzpblog.com/category/code/systemoperation/apache">Apache</a></li>
            <li id="category-item-953" class="category-item category-item-type-taxonomy category-item-object-category category-item-953"><a href="https://www.gzpblog.com/category/code/systemoperation/nginx">Nginx</a></li>
            <li id="category-item-954" class="category-item category-item-type-taxonomy category-item-object-category category-item-954"><a href="https://www.gzpblog.com/category/code/sql/mysql">MySQL</a></li>
            <li id="category-item-957" class="category-item category-item-type-taxonomy category-item-object-category category-item-957"><a href="https://www.gzpblog.com/category/code/library-expand/memcache">Memcache</a></li>
            <li id="category-item-955" class="category-item category-item-type-taxonomy category-item-object-category category-item-955"><a href="https://www.gzpblog.com/category/code/sql/redis">Redis</a></li>
            <li id="category-item-966" class="category-item category-item-type-taxonomy category-item-object-category category-item-966"><a href="https://www.gzpblog.com/category/code/front-about">前端综合</a></li>
            <li id="category-item-967" class="category-item category-item-type-taxonomy category-item-object-category category-item-967"><a href="https://www.gzpblog.com/category/code/back-about">后端综合</a></li>
            <li id="category-item-968" class="category-item category-item-type-taxonomy category-item-object-category category-item-968"><a href="https://www.gzpblog.com/category/code/code-learning">学习笔记</a></li>
        </ul>
    </div>

    <div class="widget widget-news d-block">
        <h4><span><i class="fa fa-leaf"></i>&nbsp;最新文章</span></h4>
        <ul class="news-list fa-ul ml-4 mb-0">
            <li class="news-item"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20171014/1225.html" title="emmmmm..好久没更新了">emmmmm..好久没更新了</a>
                </p>
            </li>
            <li class="news-item"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170801/1186.html" title="火狐浏览器X-Content-Type-Options导致Images类型无法加载">火狐浏览器X-Content-Type-Options导致Images类型无法加载</a>
                </p>
            </li>
            <li class="news-item"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170731/1175.html" title="Guzzle：PHP的HTTP客户端">Guzzle：PHP的HTTP客户端</a>
                </p>
            </li>
            <li class="news-item"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170720/1166.html" title="用Workerman快速实现Socket服务">用Workerman快速实现Socket服务</a>
                </p>
            </li>
            <li class="news-item"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170718/1161.html" title="「PSR 规范」关于PHP标准规范">「PSR 规范」关于PHP标准规范</a>
                </p>
            </li>
            <li class="news-item"><i class="fa-li fa fa-angle-double-right"></i>
                <p>
                    <a href="https://www.gzpblog.com/20170718/1151.html" title="消息队列及PHP中的简单实现与应用">消息队列及PHP中的简单实现与应用</a>
                </p>
            </li>
        </ul>
    </div>

    <div class="widget widget-comments d-block clearfix">
        <h4><span><i class="fa fa-comments"></i>&nbsp;最新评论</span></h4>
        <ul class="comments-list list-unstyled m-0">
            <li class="comments-item media m-1">
                <img class="avatar avatar-43  img-fluid rounded-circle"  alt="forever0121" src="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=86&amp;r=g 2x">
                <div class="comments-body  media-body ml-2 text-truncate">
                    <p class="comments-name font-weight-bold m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">forever0121</a>
                    </p>
                    <p class="comments-comment text-truncate m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">
                            请问博主为什么我输入docker-compose -version会报错，报错信息UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)
                            Failed to execute script docker-compose
                        </a>
                    </p>
                </div>
            </li>
            <li class="comments-item media m-1">
                <img class="avatar avatar-43  img-fluid rounded-circle"  alt="forever0121" src="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=86&amp;r=g 2x">
                <div class="comments-body  media-body ml-2 text-truncate">
                    <p class="comments-name font-weight-bold m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">forever0121</a>
                    </p>
                    <p class="comments-comment text-truncate m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">
                            请问博主为什么我输入docker-compose -version会报错，报错信息UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)
                            Failed to execute script docker-compose
                        </a>
                    </p>
                </div>
            </li>
            <li class="comments-item media m-1">
                <img class="avatar avatar-43  img-fluid rounded-circle"  alt="forever0121" src="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=86&amp;r=g 2x">
                <div class="comments-body  media-body ml-2 text-truncate">
                    <p class="comments-name font-weight-bold m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">forever0121</a>
                    </p>
                    <p class="comments-comment text-truncate m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">
                            请问博主为什么我输入docker-compose -version会报错，报错信息UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)
                            Failed to execute script docker-compose
                        </a>
                    </p>
                </div>
            </li>
            <li class="comments-item media m-1">
                <img class="avatar avatar-43  img-fluid rounded-circle"  alt="forever0121" src="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=86&amp;r=g 2x">
                <div class="comments-body  media-body ml-2 text-truncate">
                    <p class="comments-name font-weight-bold m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">forever0121</a>
                    </p>
                    <p class="comments-comment text-truncate m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">
                            请问博主为什么我输入docker-compose -version会报错，报错信息UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)
                            Failed to execute script docker-compose
                        </a>
                    </p>
                </div>
            </li>
            <li class="comments-item media m-1">
                <img class="avatar avatar-43  img-fluid rounded-circle"  alt="forever0121" src="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=43&amp;r=g" srcset="https://secure.gravatar.com/avatar/152aca97113f3bde32a65eefaeb9a859?s=86&amp;r=g 2x">
                <div class="comments-body  media-body ml-2 text-truncate">
                    <p class="comments-name font-weight-bold m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">forever0121</a>
                    </p>
                    <p class="comments-comment text-truncate m-0">
                        <a href="https://www.gzpblog.com/20170705/1126.html#comment-4411">
                            请问博主为什么我输入docker-compose -version会报错，报错信息UnicodeDecodeError: 'ascii' codec can't decode byte 0xc1 in position 7: ordinal not in range(128)
                            Failed to execute script docker-compose
                        </a>
                    </p>
                </div>
            </li>
        </ul>
    </div>

    <div class="widget widget-static d-block">
        <h4><span><i class="fa fa-fire"></i>&nbsp;统计</span></h4>

    </div>
</div>