<!-- 页头 -->
<section class="content-header">
    <h1>
        Fixed Layout
        <small>Blank example to the fixed layout</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Layout</a></li>
        <li class="active">Fixed</li>
    </ol>
</section>

<!-- 主内容 -->
<section class="content">
    <?php echo $this->getContent(); ?>
</section>

